npmScopes:
  zendesk:
    npmPublishRegistry: 'https://zdrepo.jfrog.io/zdrepo/api/npm/npm/'
    npmRegistryServer: 'https://zdrepo.jfrog.io/zdrepo/api/npm/npm/'

nodeLinker: node-modules

plugins:
  - .yarn/plugins/artifactory-auth.js
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall-dev.cjs
    spec: 'https://raw.githubusercontent.com/sachinraja/yarn-plugin-postinstall-dev/main/bundles/%40yarnpkg/plugin-postinstall-dev.js'
